### ISSUE TITLE
Using Locale-helper-android in fragment

### ISSUE THREAD

**Issue by CodeIsmail** [zeugma-solutions/locale-helper-android#16]
I wondering how it will be possible to use this library in fragment

**Comment by gunhansancar** [comment]
There is no special requirement to use in a fragment. Since the fragments are basically attached to the Activities, once the activity is restarted the fragments will also be restarted and will pick up the new language. I have to close this issue since this is not an issue. If you encounter a particular problem feel free to open a new ticket.
