### ISSUE TITLE
Supertypes of the following classes cannot be resolved

### ISSUE THREAD

**Issue by u84six** [zeugma-solutions/locale-helper-android#2]
Hello,
I've got a requirement in my app (yes, I'm new to Android) to switch locales within the app and found your library. I've followed the setup instructions: added dependency to build.gradle, create app, and BaseActivity, added app name to android.manifest. But when I compile, I get the error:

"Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:     class com.zeugmasolutions.localehelper.LocaleAwareCompatActivity, unresolved supertypes: androidx.appcompat.app.AppCompatActivity"

Do you know what could be causing this? I'm using Android Studio 3.4.2, min sdk 22, and Kotlin.

**Comment by gunhansancar** [comment]
Hi there, `androidx.appcompat.app.AppCompatActivity` is the new support library package name. They announced it last year. So most probably your project is old. You can either update your project to use latest `androidx` support library, actually it is the same support library but they changed the namespaces, or you can use the `delegates` method that I described in the option 2.

**For your reference migrating to the `androidx` [use this link](https://developer.android.com/jetpack/androidx/migrate) to see the official documentation.

**Comment by u84six** [comment]
This is a new project, started from scratch with latest Android Studio. Do you mean that I need to use a higher level sdk? My target is 26

**Comment by gunhansancar** [comment]
No, it is not about min SDK level. 
When you are about to create a new project, in the template, it asks you to click `Use androidx artifacts`. I guess you have not selected that option. I suggest you to migrate `androidx` because it is the way forward, or create a new project with `androidx` option selected if you are at the beginning of your project.

See the screenshot below
![image](https://user-images.githubusercontent.com/4409219/62277842-e1285680-b43e-11e9-95e9-4d30a95193e5.png)

**Comment by u84six** [comment]
I ended up just going with the delegate solution, only because I'm worried about migrating to androidx at this point. But thanks, everything is working!
