### ISSUE TITLE
How to switch back to system default locales?

### ISSUE THREAD

**Issue by thubalek** [zeugma-solutions/locale-helper-android#22]
Hi, 

I'm considering to use this library in my projects but I didn't find way how to switch back to original system settings? What value should be set to `updateLocale` method if I don't want to override system settings anymore?

Rationale: users may try this feature but find that localization to any language from the list does not fit them. So they want to return back to original state before they tried the feature. But I don't know how to implement that.

Thanks for your help
Tom

**Comment by gunhansancar** [comment]
Hi @thubalek,

It is pretty rare scenario but it is easy to handle. Because if you give the user option to change language on the fly you present them let say x amount of languages. When they select a language they can always select their native language from the list again. 

So if you want to mark the system language for the user for instance, you can do that easily.
When the app first loads, the `Locale` is filled statically by the system default. So `Locale.getDefault()` returns the system language at the beginning. The idea is you save this information somewhere and use it later on. If this is useful I can directly return it from the library itself actually. 

In your custom `Application` class, override the `attachBaseContext` method and before calling the super save the systemLocale.
```
    override fun attachBaseContext(base: Context) {
        val systemLocale = Locale.getDefault()
        super.attachBaseContext(localeAppDelegate.attachBaseContext(base))
    }
```
After that point though, Locale is overridden by the library.

**Comment by thubalek** [comment]
Thanks a lot.

**Comment by thubalek** [comment]
BTW: Not sure whether this will be sufficient if user changed locales in phone settings. Is `Application` recreated then?

**Comment by gunhansancar** [comment]
I haven't tested that but I would assume that `onConfigurationChange` would be triggered on the Application class. 
But why would anyone change their device's language? IMHO you're focusing on something insignificant. 

It seems to me that you need some sort of on/off switch for the `LocaleHelper`

**Comment by dzboot02** [comment]
You can pass the locale below to achieve what you want:

`ConfigurationCompat.getLocales(Resources.getSystem().configuration)[0]`

**Comment by thubalek** [comment]
> It seems to me that you need some sort of on/off switch for the LocaleHelper

@gunhansancar yeah, that would be great.

**Comment by thubalek** [comment]
> But why would anyone change their device's language? 

I'm doing it sometimes. My mother tongue is Czech but I sometimes need screenshot in English to share it with people don't speak Czech. I switch locale to English and back when communication finished.

**Comment by gunhansancar** [comment]
From the library I can store the initial device language at the startup. And then I think you can use it to set back to device original language using e.g.
`LocaleHelper.getSystemLanguage()` would that be useful in your case?

**Comment by gunhansancar** [comment]
Added `systemLocale` to the `LocaleHelper` in the version `1.1.3` so that yo ucan switch back to the original locale afterwards
