### ISSUE TITLE
Application context resources not localized after a runtime locale change

### ISSUE THREAD

**Issue by Tameki** [zeugma-solutions/locale-helper-android#28]
``` Kotlin
getString(R.string.main_activity_title) - always returns valid string as expected
applicationContext.getString(R.string.main_activity_title) - returns only initial locale string
```

Could you provide any information on this issue?

**Comment by Tameki** [comment]
I assume that this issue refers to #24 issue fix?

**Comment by Tameki** [comment]
Or we are gonna need to use a workaround from #1 issue?

**Comment by gunhansancar** [comment]
Hi @Tameki, I'm looking into it also I wonder what's the reason you use `applicationContext` inside the `Activity` ?

**Comment by Tameki** [comment]
Hi @gunhansancar, this is just for the case of using `applicationContext` anywhere in application like `StringResourcesManager` as pointed out in issue #1

**Comment by gunhansancar** [comment]
The problem about `Application` is that it is already a `ContextWrapper` implementation. And if we create a new context using `createConfigurationContext` it is no longer a subclass of `Application`. 

This is no problem if you only need `Application` as a `Context` however in issue #24 the application is being used as custom application using a typecast but obviously it is no longer a subclass of `Application`. That's why I removed `Application` context localization. But in your case it is needed :) 

However, even if we do enable application context wrapping it is still not enough in your case because if your `StringResourceManager` is a singleton it would have the previous `Configuration` inside its `Context`. So as in #1 you have to update the `Context.resources` manually.

**Comment by Tameki** [comment]
Ok, got it :) Thanks for response) I assume that It would be cool to add a note about using applicationContext to get resources in README.md to decrease miss understanding or link to this issue)

**Comment by gunhansancar** [comment]
When I have more time, I'll try to add a listener approach to notify changes to the static classes. 

If you're using Dagger, you could provide Activity context to your `resourcemanager` using custom scopes. That way it can be consumed in `ViewModel` without leaking the context. However, it is more about the dagger modules/components.
