### ISSUE TITLE
On Android 9, a black screen appears when activity is recreated

### ISSUE THREAD

**Issue by ali991** [zeugma-solutions/locale-helper-android#3]

**Comment by gunhansancar** [comment]
I tried with Pixel 2 API 28(Android 9.0) simulator and it is working fine.
On the activity recreate it restarts it and a black screen appears momentarily and then the new activity with the new locale appears. 
What do you expect?

**Comment by ali991** [comment]
Yes exactly, Is there any solution to not show this black screen ?

**Comment by gunhansancar** [comment]
You can check [this](https://gunhansancar.com/change-language-programmatically-in-android/) out. I describe in there how to update the resources manually if you want to avoid activity recreate. Basically, you have to find all the resources on the screen and update them manually. 

But from this library's perspective, I cannot help you, like automatically find the resources and update them because there is no way to tell after assigning values to them.

**Comment by gunhansancar** [comment]
I'm closing the issue as it is not possible to interfere the system behaviour from the library itself.
