### ISSUE TITLE
Getting string resources using application context returns string resource in previously selected language 

### ISSUE THREAD

**Issue by momersaleem** [zeugma-solutions/locale-helper-android#30]
Hello,

I have Arabic and English string resources. On app start, default language is English and accessing a string resource using application context returns English string. This is how accessing string resource using AC.
applicationContext.resources.getString(R.string.economic_department)

Now changing app language to Arabic using the following code and restart launcher activity again from fragment.
**Settings Fragment**
LocaleHelper.setLocale(mContext, Locale("ar")) 
(activity as HomeActivity).restartHomeActivity()

**HomeActivity**
fun restartHomeActivity() {
        finish()
        val newIntent = intent
        newIntent.flags = Intent.FLAG_ACTIVITY_CLEAR_TOP
        startActivity(newIntent)
    }

On restart, accessing the same resource again for Arabic language still returns the English versioned string resource. Please guide?

**Comment by gunhansancar** [comment]
`Application context` is not updated even after you restart your activity. 
The best approach is to use `Activity context` which is always updated with latest Locale.

This is not about how this library works. It is how Android works.

If you really want to use applicationContext then you have to wrap it every time before using it:

`LocaleHelper.onAttach(applicationContext)` which returns an updated `Context` but it should be **avoided** if you use it pretty often because of the performance implications.
