### ISSUE TITLE
Activities are created twice

### ISSUE THREAD

**Issue by ykrapiva** [zeugma-solutions/locale-helper-android#5]
I've followed **(Option 1) Using base classes**

Now I see that my activities are created twice, because they are recreated in LocaleHelperDelegates.kt:41 - onResume().
So, I see a short blink each time I open another activity.
I don't understand if that's expected or I've missed something ?

**Comment by kibotu** [comment]
activty.recreate happens during LocaleHelperActivityDelegateImpl#setLocale so it should be fine to only use that method when updating locale by user actions imho 

not sure why it is necessary to update locale in onPause and onResume 

any idea?

**Comment by gunhansancar** [comment]
Hi @kibotu,

We have to save the active locale at the time `onPause` called because when the activity is added to backstack, there is noway to tell if that activity is using locale-a or locale-b. So when that activity is popped from the stack `onResume` is called and, if the locale is changed on the other activities, we can that way force to update the locale by checking if it is changed or not.

**Comment by gunhansancar** [comment]
Hi @ykrapiva,

Could you tell me what android version you're using so that I can test and verify?

**Comment by kibotu** [comment]
ah ok, i was thinking of a single activity application which only changes locales based on active user interaction. 

but of course configuration changes can happen in other uses cases i see that now, thanks for explaining :) @gunhansancar

**Comment by gunhansancar** [comment]
Closing the issue as I tested on API level 21, 24, 26, 28, 29 couldn't achieve double activity creation. 

The blinking issue happens on and after API level 28. Most probably `activity.recreate()` implementation is changed.
